// Ported from misiahmiles-ui/leanmaster-note-engine@ef76ca0735ed841e82fa98eed48420724709468b
// Original: src/server/prompts/treatmentPlanPromptRules.ts. Only module import paths are adapted.
export const treatmentPlanPromptRules = `
19. DAP/SOAP Plan and formal treatment-plan distinction
19.1. The Plan section remains the P inside a DAP or SOAP progress note. It documents encounter-level interventions, referrals, homework, and next steps arising from that service contact.
19.2. Never label or represent a DAP or SOAP Plan section as the member's formal treatment plan, individualized treatment plan, or individualized plan of care.
19.3. Generate a formal Treatment Plan only when the user selects Treatment Plan as the Documentation Type. Use the same normal one-pass workflow used for other documentation types: process the clinician-entered de-identified Session Data / Program Context and selected fields through the AI note engine, then return the completed Treatment Plan in that response.
19.4. A prior DAP note, SOAP note, quarterly note, or separately processed result is not required for the standalone Treatment Plan documentation type. Do not append a Treatment Plan to another note unless the user explicitly selects Progress Note - DAP Format / Treatment Plan or Progress Note - SOAP Format / Treatment Plan.
19.5. Use only the facts supported by the Session Data / Program Context and selected fields. Organize and clinically formulate those facts according to the selected discipline, but do not invent or add unsupported diagnoses, risks, needs, strengths, functional concerns, recommendations, goals, objectives, or interventions.
19.6. For each treatment problem supported by the session information, use only these exact headings in this exact order: I. LONG-TERM GOAL; II. SHORT-TERM OBJECTIVES; III. INTERVENTIONS. Repeat the complete three-part structure only when the session information supports more than one distinct treatment problem.
19.7. For each supported treatment problem, generate one clinically appropriate long-term goal, two or three specific and measurable short-term objectives, and two or three evidence-based, discipline-appropriate interventions. Every item must be traceable to the submitted session information.
19.8. Keep the treatment plan concise, individualized, professional, and suitable for Adult Medical Day Care. Do not add demographics, a primary-needs summary, service frequency, expected outcomes, signatures, approvals, target dates, review schedules, progress-measurement sections, participant-involvement sections, resources, support modules, or any other section.
19.9. Progress notes may identify the existing treatment-plan goal addressed and document progress or barriers, but they must not silently create, replace, amend, or finalize the formal treatment plan.
19.10. Treatment-plan drafts require review and approval by authorized professionals according to role, setting, payer requirements, and organization policy. LeanMaster does not determine eligibility, medical necessity, authorization, or compliance.
19.11. An Activities Care Plan Contribution remains a discipline-specific contribution and is not automatically the complete interdisciplinary treatment plan or plan of care.
19.12. When Progress Note - DAP Format / Treatment Plan or Progress Note - SOAP Format / Treatment Plan is selected, first generate the complete discipline-appropriate progress note from the submitted Session Data / Program Context. Only after that progress note is complete, develop the individualized Treatment Plan solely from the facts, findings, treatment needs, strengths, barriers, risks, and interventions documented in that generated progress note.
19.13. For a combined progress-note/treatment-plan request, return both documents in one response and one generation pass. Keep the progress note first. Then use the exact Treatment Plan headings from 19.6. Do not independently reinterpret the raw Session Data when developing the Treatment Plan, and do not introduce content that is absent from the generated progress note.
19.14. The treatment-plan language must remain appropriate to the selected discipline. Preserve LSW, LCSW, supervised social-work, nursing, counseling, and other role boundaries already defined by the engine.
19.15. Do not state that the member agreed, will, plans to, or committed to a treatment-plan action unless that commitment is documented in the completed progress note. When no agreement is documented, write the objective as a proposed measurable target rather than an invented client commitment.
` as const;
